spring:
  application:
    name:demo
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: testdb
    main:
      allow-bean-definition-overriding: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

server:
  port: 8080